# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习and学校\搞事情\LAE\timeline\ui文件\basicStateRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.yes_button = QtWidgets.QPushButton(Dialog)
        self.yes_button.setGeometry(QtCore.QRect(20, 250, 75, 24))
        self.yes_button.setObjectName("yes_button")
        self.tiredness_label = QtWidgets.QLabel(Dialog)
        self.tiredness_label.setGeometry(QtCore.QRect(20, 20, 54, 16))
        self.tiredness_label.setObjectName("tiredness_label")
        self.exhaustion_label = QtWidgets.QLabel(Dialog)
        self.exhaustion_label.setGeometry(QtCore.QRect(20, 60, 54, 16))
        self.exhaustion_label.setObjectName("exhaustion_label")
        self.anxiety_label = QtWidgets.QLabel(Dialog)
        self.anxiety_label.setGeometry(QtCore.QRect(20, 100, 54, 16))
        self.anxiety_label.setObjectName("anxiety_label")
        self.vitality_label = QtWidgets.QLabel(Dialog)
        self.vitality_label.setGeometry(QtCore.QRect(20, 140, 54, 16))
        self.vitality_label.setObjectName("vitality_label")
        self.activeness_label = QtWidgets.QLabel(Dialog)
        self.activeness_label.setGeometry(QtCore.QRect(20, 180, 61, 16))
        self.activeness_label.setObjectName("activeness_label")
        self.tiredness_entry = QtWidgets.QLineEdit(Dialog)
        self.tiredness_entry.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.tiredness_entry.setObjectName("tiredness_entry")
        self.exhaustion_entry = QtWidgets.QLineEdit(Dialog)
        self.exhaustion_entry.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.exhaustion_entry.setObjectName("exhaustion_entry")
        self.anxiety_entry = QtWidgets.QLineEdit(Dialog)
        self.anxiety_entry.setGeometry(QtCore.QRect(110, 100, 113, 20))
        self.anxiety_entry.setObjectName("anxiety_entry")
        self.vitality_entry = QtWidgets.QLineEdit(Dialog)
        self.vitality_entry.setGeometry(QtCore.QRect(110, 140, 113, 20))
        self.vitality_entry.setObjectName("vitality_entry")
        self.activeness_entry = QtWidgets.QLineEdit(Dialog)
        self.activeness_entry.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.activeness_entry.setObjectName("activeness_entry")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "记录基础状态"))
        self.yes_button.setText(_translate("Dialog", "生成记录"))
        self.tiredness_label.setText(_translate("Dialog", "困倦度"))
        self.exhaustion_label.setText(_translate("Dialog", "脑损度"))
        self.anxiety_label.setText(_translate("Dialog", "焦虑度"))
        self.vitality_label.setText(_translate("Dialog", "体力值"))
        self.activeness_label.setText(_translate("Dialog", "积极愉悦度"))
