# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习and学校\搞事情\LAE\timeline\ui文件\end_period.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 236)
        self.yes_button = QtWidgets.QPushButton(Dialog)
        self.yes_button.setGeometry(QtCore.QRect(30, 30, 75, 24))
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(Dialog)
        self.no_button.setGeometry(QtCore.QRect(30, 100, 75, 24))
        self.no_button.setObjectName("no_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "是否结束当前时段"))
        self.yes_button.setText(_translate("Dialog", "yes"))
        self.no_button.setText(_translate("Dialog", "no"))
