# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习and学校\搞事情\LAE\timeline\ui文件\list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_time_period_and_activity(object):
    def setupUi(self, time_period_and_activity):
        time_period_and_activity.setObjectName("time_period_and_activity")
        time_period_and_activity.resize(740, 499)
        self.activity_list = QtWidgets.QListWidget(time_period_and_activity)
        self.activity_list.setGeometry(QtCore.QRect(60, 80, 256, 192))
        self.activity_list.setObjectName("activity_list")
        item = QtWidgets.QListWidgetItem()
        self.activity_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.activity_list.addItem(item)

        self.retranslateUi(time_period_and_activity)
        QtCore.QMetaObject.connectSlotsByName(time_period_and_activity)

    def retranslateUi(self, time_period_and_activity):
        _translate = QtCore.QCoreApplication.translate
        time_period_and_activity.setWindowTitle(_translate("time_period_and_activity", "Dialog"))
        __sortingEnabled = self.activity_list.isSortingEnabled()
        self.activity_list.setSortingEnabled(False)
        item = self.activity_list.item(0)
        item.setText(_translate("time_period_and_activity", "ababab"))
        item = self.activity_list.item(1)
        item.setText(_translate("time_period_and_activity", "sdssd"))
        self.activity_list.setSortingEnabled(__sortingEnabled)
