# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习and学校\搞事情\LAE\timeline\ui文件\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(0, 0, 381, 571))
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.current_period_name_label = QtWidgets.QLabel(self.left_frame)
        self.current_period_name_label.setGeometry(QtCore.QRect(20, 10, 131, 20))
        self.current_period_name_label.setObjectName("current_period_name_label")
        self.show_plan_button = QtWidgets.QPushButton(self.left_frame)
        self.show_plan_button.setGeometry(QtCore.QRect(50, 360, 141, 31))
        self.show_plan_button.setObjectName("show_plan_button")
        self.basic_state_record_button = QtWidgets.QPushButton(self.left_frame)
        self.basic_state_record_button.setGeometry(QtCore.QRect(50, 420, 141, 41))
        self.basic_state_record_button.setObjectName("basic_state_record_button")
        self.plan_text = QtWidgets.QTextEdit(self.left_frame)
        self.plan_text.setGeometry(QtCore.QRect(20, 60, 341, 271))
        self.plan_text.setObjectName("plan_text")
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(380, 0, 421, 581))
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.start_new_period_button = QtWidgets.QPushButton(self.right_frame)
        self.start_new_period_button.setGeometry(QtCore.QRect(30, 10, 101, 24))
        self.start_new_period_button.setObjectName("start_new_period_button")
        self.end_current_period_button = QtWidgets.QPushButton(self.right_frame)
        self.end_current_period_button.setGeometry(QtCore.QRect(30, 40, 101, 24))
        self.end_current_period_button.setObjectName("end_current_period_button")
        self.close_button = QtWidgets.QPushButton(self.right_frame)
        self.close_button.setGeometry(QtCore.QRect(30, 70, 101, 24))
        self.close_button.setObjectName("close_button")
        self.activity_list = QtWidgets.QListWidget(self.right_frame)
        self.activity_list.setGeometry(QtCore.QRect(30, 140, 256, 192))
        self.activity_list.setObjectName("activity_list")
        self.current_activity_name_label = QtWidgets.QLabel(self.right_frame)
        self.current_activity_name_label.setGeometry(QtCore.QRect(30, 360, 171, 20))
        self.current_activity_name_label.setObjectName("current_activity_name_label")
        self.new_activity_button = QtWidgets.QPushButton(self.right_frame)
        self.new_activity_button.setGeometry(QtCore.QRect(30, 410, 75, 24))
        self.new_activity_button.setObjectName("new_activity_button")
        self.end_activity_button = QtWidgets.QPushButton(self.right_frame)
        self.end_activity_button.setGeometry(QtCore.QRect(160, 410, 75, 24))
        self.end_activity_button.setObjectName("end_activity_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.current_period_name_label.setText(_translate("MainWindow", "current_period_name"))
        self.show_plan_button.setText(_translate("MainWindow", "show plan"))
        self.basic_state_record_button.setText(_translate("MainWindow", "记录基本状态"))
        self.start_new_period_button.setText(_translate("MainWindow", "开启新时段"))
        self.end_current_period_button.setText(_translate("MainWindow", "结束当前时段"))
        self.close_button.setText(_translate("MainWindow", "Close"))
        self.current_activity_name_label.setText(_translate("MainWindow", "current_activity_name"))
        self.new_activity_button.setText(_translate("MainWindow", "新活动"))
        self.end_activity_button.setText(_translate("MainWindow", "结束活动"))
