# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习and学校\搞事情\LAE\timeline\ui文件\new_period.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(366, 235)
        self.by_set_button = QtWidgets.QPushButton(Dialog)
        self.by_set_button.setGeometry(QtCore.QRect(30, 180, 81, 24))
        self.by_set_button.setObjectName("by_set_button")
        self.recommend_period_label = QtWidgets.QLabel(Dialog)
        self.recommend_period_label.setGeometry(QtCore.QRect(30, 30, 54, 16))
        self.recommend_period_label.setObjectName("recommend_period_label")
        self.entry_label = QtWidgets.QLabel(Dialog)
        self.entry_label.setGeometry(QtCore.QRect(30, 70, 141, 16))
        self.entry_label.setObjectName("entry_label")
        self.new_period_entry = QtWidgets.QLineEdit(Dialog)
        self.new_period_entry.setGeometry(QtCore.QRect(30, 100, 113, 20))
        self.new_period_entry.setObjectName("new_period_entry")
        self.by_recommend_button = QtWidgets.QPushButton(Dialog)
        self.by_recommend_button.setGeometry(QtCore.QRect(150, 180, 101, 24))
        self.by_recommend_button.setObjectName("by_recommend_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "开启新时段!"))
        self.by_set_button.setText(_translate("Dialog", "by set"))
        self.recommend_period_label.setText(_translate("Dialog", "TextLabel"))
        self.entry_label.setText(_translate("Dialog", "请输入指定的period编号:"))
        self.by_recommend_button.setText(_translate("Dialog", "by recommend"))
